matrix:
  include:
    - language: python
     python: 2.7
     install:
       - pip install -r requirements.txt
     before_script:
       - cd/server/test/preprocessing
     script:
       - dataTransform.py
        
    - language: node_js
      node_js: "7"
      script: App.test.js
    
    -language:
